# Generated by Django 4.2.11 on 2026-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_donhang_options_remove_donhang_bat_dau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donhang',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
