# Generated by Django 4.2.7 on 2026-04-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_donhang_lat_donhang_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaiDatHeThong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia_cuoc_km', models.IntegerField(default=5000, verbose_name='Giá cước (VNĐ/km)')),
                ('gio_bat_dau', models.IntegerField(default=8, verbose_name='Giờ bắt đầu làm việc')),
                ('gio_ket_thuc', models.IntegerField(default=17, verbose_name='Giờ kết thúc làm việc')),
                ('so_xe_toi_da', models.IntegerField(default=3, verbose_name='Số xe tối đa')),
                ('tai_trong_toi_da', models.IntegerField(default=500, verbose_name='Tải trọng tối đa/xe (kg)')),
                ('thuat_toan_mac_dinh', models.CharField(choices=[('greedy', 'Nearest Neighbor (Tham lam)'), ('clarke_wright', 'Clarke-Wright (Tiết kiệm)'), ('genetic', 'Genetic Algorithm (Di truyền)')], default='greedy', max_length=50, verbose_name='Thuật toán mặc định')),
                ('tu_dong_toi_uu', models.BooleanField(default=False, verbose_name='Tự động tối ưu lộ trình')),
                ('cap_nhat_luc', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cài đặt hệ thống',
                'verbose_name_plural': 'Cài đặt hệ thống',
            },
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khung_gio_muon',
            field=models.IntegerField(blank=True, default=18, null=True, verbose_name='Giờ muộn nhất (0-24)'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='khung_gio_som',
            field=models.IntegerField(blank=True, default=8, null=True, verbose_name='Giờ sớm nhất (0-24)'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='thoi_gian_phuc_vu',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='TG phục vụ (phút)'),
        ),
    ]
